---
title: microcontroller projects
description: > # this means to ignore newlines until "baseurl:"
  projects with PIC microcontrollers
baseurl: ""
url: "https://tahull.github.io"
repository: tahull/tahull.github.io
#github_username:
#excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Custom
current_version:      0.0.54

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
