---
title: microcontroller projects
description: projects with PIC microcontrollers
baseurl: ""
url: "https://tah83.github.io"
repository: tah83/tah83.github.io
#github_username:

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Custom
current_version:      0.0.25

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
